### ISSUE TITLE
Using this plugin with a proxy.

### ISSUE THREAD

**Issue by ChristopheChirat** [awslabs/collectd-cloudwatch#31] opened 2016-12-22 15:11 UTC
Hi folks,

I can not expose all my servers on the internet to send the data to Cloudwatch. Therefore, how could I configure a proxy that could centralize data and be the only server exposed to the Internet?

Thanks for your feedback.

**Comment by sebasrp** [comment] 2017-02-02 12:45
closing as duplicate of #20

**Closed by sebasrp** 2017-02-02 12:45 UTC
Labels: duplicate
